namespace KerkenezMail.Languages
{
    /// <summary>
    /// Master English (en) language definition for Kerkenez Mail.
    /// Acts as the default fallback language across the entire application.
    /// </summary>
    public class EnglishLanguage : BaseLanguage
    {
        public override string Code => "en";
        public override string Name => "English";
        public override string EnglishName => "English";
        public override string FlagEmoji => "🇬🇧";

        protected override void InitTranslations()
        {
            // ==============================================================================
            // KEY                                       TRANSLATION
            // ==============================================================================

            // --- 1. Navigation & Sidebar ---
            Set(StringKeys.NavInbox,                     "Inbox");
            Set(StringKeys.NavSendMail,                  "Send Mail");
            Set(StringKeys.NavAccounts,                  "Accounts");
            Set(StringKeys.NavSettings,                  "Settings");
            Set(StringKeys.NavLiveLogs,                  "Live Logs");
            Set(StringKeys.NavSent,                      "Sent");
            Set(StringKeys.NavArchived,                  "Archived");
            Set(StringKeys.NavSpam,                      "Spam");
            Set(StringKeys.NavTrash,                     "Trash");
            Set(StringKeys.NavLiveImap,                  "Live IMAP");
            Set(StringKeys.NavLiveImapActive,            "Live IMAP is active (Click to turn off)");
            Set(StringKeys.NavLiveImapOff,               "Live IMAP is off (Click to turn on)");
            Set(StringKeys.NavTipExpandSidebar,          "Expand sidebar (Ctrl+B)");
            Set(StringKeys.NavTipCollapseSidebar,        "Collapse sidebar (Ctrl+B)");
            Set(StringKeys.NavTipExpandFolders,          "Expand mail folders (Sent, Archive, Trash...)");
            Set(StringKeys.NavTipCollapseFolders,        "Collapse mail folders");

            // --- 2. Main Window & Shell ---
            Set(StringKeys.AppTitle,                     "Kerkenez Mail (Win32)");
            Set(StringKeys.MainShortcutsPromptTitle,     "Kerkenez Mail Shortcuts");
            Set(StringKeys.MainShortcutsPromptDesc,      "Welcome to Kerkenez Mail!\r\n\r\nWould you like to create shortcuts on your Desktop and Start Menu for easy access?");
            Set(StringKeys.TrayOpen,                     "📬  Open Kerkenez Mail");
            Set(StringKeys.TrayLiveImapActive,           "⚡  Live IMAP: Active (Click to toggle)");
            Set(StringKeys.TrayLiveImapOff,              "💤  Live IMAP: Idle (Click to toggle)");
            Set(StringKeys.TrayCheckNow,                 "🔄  Check Now");
            Set(StringKeys.TraySettings,                 "⚙️  Settings");
            Set(StringKeys.TrayExit,                     "❌  Exit");

            // --- 3. Inbox & Summaries View ---
            Set(StringKeys.InboxRefresh,                 "Refresh");
            Set(StringKeys.InboxCopySummary,             "Copy Summary");
            Set(StringKeys.InboxExport,                  "Export...");
            Set(StringKeys.InboxOpenInBrowser,           "Open in Browser");
            Set(StringKeys.InboxTipRefresh,              "Refresh Inbox: Fetch new messages from configured accounts");
            Set(StringKeys.InboxTipCopySummary,          "Copy Summary: Copy the AI executive summary to clipboard");
            Set(StringKeys.InboxTipExport,               "Export: Save emails and summaries to JSON, CSV, Markdown, or HTML report");
            Set(StringKeys.InboxTipOpenInBrowser,        "Open in Browser: View original email in default browser (Full HTML with remote images & styles)");
            Set(StringKeys.InboxTipArchive,              "Archive: Move selected email(s) to Archive folder");
            Set(StringKeys.InboxTipDelete,               "Delete: Move selected email(s) to Trash folder");
            Set(StringKeys.InboxTipReply,                "Reply: Compose a reply to this email thread");
            Set(StringKeys.InboxTipMoveToInbox,          "Move to Inbox: Move selected email(s) back to Inbox");
            Set(StringKeys.InboxAccountLabel,            "Account:");
            Set(StringKeys.InboxAllAccounts,             "All Accounts");
            Set(StringKeys.InboxListHeader,              "{0} ({1} emails)");
            Set(StringKeys.InboxListHeaderUnread,        "{0} ({1} emails, {2} unread)");
            Set(StringKeys.InboxSubjectPrefix,           "Subject:");
            Set(StringKeys.InboxNoEmailSelected,         "(No email selected)");
            Set(StringKeys.InboxAiExecutiveSummary,      "AI Executive Summary");
            Set(StringKeys.InboxAiGeneratedVram,         "(Generated by local LLM in VRAM)");
            Set(StringKeys.InboxAiSummaryPlaceholder,    "AI summary will appear here...");
            Set(StringKeys.InboxAttachmentsTitle,        "Attachments:");
            Set(StringKeys.InboxTagRead,                 "Read");
            Set(StringKeys.InboxTagUnread,               "Unread");
            Set(StringKeys.InboxTagArchived,             "Archived");
            Set(StringKeys.InboxSummarize,               "AI Summarize");
            Set(StringKeys.InboxSearchPlaceholder,       "Search emails by sender, subject, or content...");
            Set(StringKeys.InboxColAccount,              "Account");
            Set(StringKeys.InboxColFrom,                 "From");
            Set(StringKeys.InboxColSubject,              "Subject");
            Set(StringKeys.InboxColDate,                 "Date");
            Set(StringKeys.InboxColPriority,             "Priority");
            Set(StringKeys.InboxPriorityHigh,            "HIGH");
            Set(StringKeys.InboxPriorityNormal,          "NORMAL");
            Set(StringKeys.InboxPriorityLow,             "LOW");
            Set(StringKeys.InboxEmptyTitle,              "No emails found");
            Set(StringKeys.InboxEmptySubtitle,           "Select an account or click Refresh to fetch emails.");
            Set(StringKeys.InboxNoSelectionTitle,        "No email selected");
            Set(StringKeys.InboxNoSelectionSubtitle,     "Choose an email from the list to view its summary and details.");
            Set(StringKeys.InboxDetailFrom,              "From:");
            Set(StringKeys.InboxDetailTo,                "To:");
            Set(StringKeys.InboxDetailDate,              "Date:");
            Set(StringKeys.InboxDetailAccount,           "Account:");
            Set(StringKeys.InboxTabSummary,              "AI Summary");
            Set(StringKeys.InboxTabOriginal,             "Original Email");
            Set(StringKeys.InboxBtnMarkRead,             "Mark Read");
            Set(StringKeys.InboxBtnMarkUnread,           "Mark Unread");
            Set(StringKeys.InboxBtnDelete,               "Delete");
            Set(StringKeys.InboxBtnMoveInbox,            "Move to Inbox");
            Set(StringKeys.InboxBtnReply,                "Reply");
            Set(StringKeys.InboxBtnForward,              "Forward");
            Set(StringKeys.InboxBtnDownloadAttachments,  "Download Attachments");
            Set(StringKeys.InboxLoadingStatus,           "Fetching emails...");
            Set(StringKeys.InboxSummarizingStatus,       "Summarizing with AI...");
            Set(StringKeys.InboxLiveActiveBadge,         "Live IMAP: Connected");
            Set(StringKeys.InboxMultiSelectCount,        "{0} emails selected");
            Set(StringKeys.InboxSavedAttachmentsToast,   "Saved {0} of {1} attachments to:\r\n{2}\r\n\r\nWould you like to open the folder?");
            Set(StringKeys.InboxSavedAttachmentsStatus,  "Saved {0}/{1} attachments");
            Set(StringKeys.InboxDownloadComplete,        "Download Complete");
            Set(StringKeys.InboxDownloadError,           "Error downloading attachments: {0}");
            Set(StringKeys.InboxSummaryCopiedToast,      "Summary copied to clipboard!");
            Set(StringKeys.InboxAllSummariesCopiedToast, "All summaries copied to clipboard in Markdown format!");
            Set(StringKeys.InboxNoSummaryToCopy,         "No summary available to copy.");
            Set(StringKeys.InboxNoEmailsToExport,        "No emails available to export.");
            Set(StringKeys.InboxExportSuccessToast,      "Successfully exported to {0}!");
            Set(StringKeys.InboxExportSuccessTitle,      "Export Succeeded");
            Set(StringKeys.InboxExportErrorToast,        "Failed to export file: {0}");
            Set(StringKeys.InboxExportErrorTitle,        "Export Error");
            Set(StringKeys.InboxBrowserErrorToast,       "Failed to open email in browser:\n{0}");
            Set(StringKeys.InboxBrowserErrorTitle,       "Browser Error");
            Set(StringKeys.InboxAccountNotFound,         "Could not locate configured email account for '{0}' ({1}).");
            Set(StringKeys.InboxDeletePermanentlyTip,    "Delete Permanently: Permanently remove selected email(s)");
            Set(StringKeys.InboxDeleteMoveTip,           "Delete: Move selected email(s) to Trash folder");
            Set(StringKeys.InboxDownloadedSingleToast,   "Successfully downloaded '{0}'!\r\n\r\nSaved to: {1}\r\n\r\nWould you like to open the containing folder?");
            Set(StringKeys.InboxDownloadedSingleStatus,  "Downloaded '{0}'");
            Set(StringKeys.InboxDownloadFailedStatus,    "Download failed");
            Set(StringKeys.InboxDownloadFailed,          "Download Failed");

            // --- 4. Send Mail / Compose ---
            Set(StringKeys.SendTitle,                    "Compose New Email");
            Set(StringKeys.SendThreadedReply,            "Threaded Reply");
            Set(StringKeys.SendBackToInbox,              "Inbox");
            Set(StringKeys.SendPopOut,                   "Pop Out");
            Set(StringKeys.SendFrom,                     "From:");
            Set(StringKeys.SendCcBccToggle,              "+ Cc / Bcc");
            Set(StringKeys.SendTo,                       "To:");
            Set(StringKeys.SendCc,                       "Cc:");
            Set(StringKeys.SendBcc,                      "Bcc:");
            Set(StringKeys.SendSubject,                  "Subject:");
            Set(StringKeys.SendToPlaceholder,            "recipient@example.com (separate multiple with comma)");
            Set(StringKeys.SendCcPlaceholder,            "Cc recipients...");
            Set(StringKeys.SendBccPlaceholder,           "Bcc recipients...");
            Set(StringKeys.SendSubjectPlaceholder,       "Subject");
            Set(StringKeys.SendBodyPlaceholder,          "Write your email message here using Markdown...\r\n\r\n# Heading\r\n**Bold**, *Italic*, `code`\r\n- Bullet points\r\n> Quoted text\r\n[Link Title](https://example.com)");
            Set(StringKeys.SendAttachments,              "Attachments:");
            Set(StringKeys.SendAddAttachment,            "Attach File");
            Set(StringKeys.SendRemoveAttachment,         "Remove");
            Set(StringKeys.SendBtnSend,                  "Send Email");
            Set(StringKeys.SendBtnDiscard,               "Discard");
            Set(StringKeys.SendBtnSaveDraft,             "Save Draft");
            Set(StringKeys.SendSending,                  "Sending email...");
            Set(StringKeys.SendSuccess,                  "Email sent successfully!");
            Set(StringKeys.SendError,                    "Failed to send email.");
            Set(StringKeys.SendAiAssist,                 "AI Polish");
            Set(StringKeys.SendDraftsTitle,              "Drafts");
            Set(StringKeys.SendTabMarkdown,              "Markdown Edit");
            Set(StringKeys.SendTabPlaintext,             "Plaintext Preview");
            Set(StringKeys.SendTabHtml,                  "HTML Preview");
            Set(StringKeys.SendFormatMultipart,          "Markdown (Text + HTML Multipart)");
            Set(StringKeys.SendFormatPlaintext,          "Plaintext Only (Raw RFC Text)");
            Set(StringKeys.SendDropHint,                 "Attach files");
            Set(StringKeys.SendBrowseFiles,              "Browse Files...");
            Set(StringKeys.SendAttachmentSummary,        "{0} attachments ({1} KB)");
            Set(StringKeys.SendStatusHint,               "Ready to compose. Markdown formatting supported.");
            Set(StringKeys.SendConfirmDiscard,           "Are you sure you want to discard this draft?");
            Set(StringKeys.SendDiscardTitle,             "Discard Draft");
            Set(StringKeys.SendToolbarBold,              "Bold (**text**)");
            Set(StringKeys.SendToolbarItalic,            "Italic (*text*)");
            Set(StringKeys.SendToolbarHeader,            "Header (### text)");
            Set(StringKeys.SendToolbarLink,              "Insert Link ([text](url))");
            Set(StringKeys.SendToolbarBulletList,        "Bullet List (- item)");
            Set(StringKeys.SendToolbarNumberedList,      "Numbered List (1. item)");
            Set(StringKeys.SendToolbarQuote,             "Quote Block (> text)");
            Set(StringKeys.SendToolbarCode,              "Code Block (```)");
            Set(StringKeys.SendToolbarRule,              "Horizontal Rule (---)");
            Set(StringKeys.SendMissingRecipient,         "Please enter at least one recipient in the 'To' field.");
            Set(StringKeys.SendMissingRecipientTitle,    "Missing Recipient");
            Set(StringKeys.SendMissingAccount,           "Please select an account to send from.");
            Set(StringKeys.SendMissingAccountTitle,      "Missing Account");
            Set(StringKeys.SendNoSubjectPrompt,          "Send this message without a subject?");
            Set(StringKeys.SendNoSubjectTitle,           "No Subject");
            Set(StringKeys.SendSentTitle,                "Email Sent");
            Set(StringKeys.SendFailedTitle,              "Failed to Send Email");

            // --- 5. Accounts View & Dialog ---
            Set(StringKeys.AccountsTitle,                "Email Accounts");
            Set(StringKeys.AccountsSubtitle,             "Manage your configured IMAP/SMTP accounts and credentials.");
            Set(StringKeys.AccountsBtnAdd,               "Add Account");
            Set(StringKeys.AccountsBtnEdit,              "Edit");
            Set(StringKeys.AccountsBtnDelete,            "Delete");
            Set(StringKeys.AccountsBtnTest,              "Test Connection");
            Set(StringKeys.AccountsColEmail,             "Email Address");
            Set(StringKeys.AccountsColProvider,          "Provider");
            Set(StringKeys.AccountsColServer,            "Incoming Server");
            Set(StringKeys.AccountsColStatus,            "Status");
            Set(StringKeys.AccountsStatusUntested,        "Untested");
            Set(StringKeys.AccountsStatusConnected,      "Connected");
            Set(StringKeys.AccountsStatusConnectedUnread,"Connected ({0} unread)");
            Set(StringKeys.AccountsStatusFailed,         "Failed");
            Set(StringKeys.AccountsStatusError,          "Connection Error");
            Set(StringKeys.AccountsEmptyDesc,            "No accounts configured yet.\r\nClick '+ Add Account' above to connect your Gmail or IMAP account.");
            Set(StringKeys.AccountsDeleteConfirm,        "Are you sure you want to remove account '{0}' ({1})?");

            Set(StringKeys.AddAccTitle,                  "Add Email Account");
            Set(StringKeys.AddAccEditTitle,              "Edit Email Account");
            Set(StringKeys.AddAccProviderPreset,         "Provider Preset:");
            Set(StringKeys.AddAccEmail,                  "Email Address:");
            Set(StringKeys.AddAccPassword,               "Password / App Password:");
            Set(StringKeys.AddAccDisplayName,            "Account Label:");
            Set(StringKeys.AddAccImapServer,             "IMAP Host & Port:");
            Set(StringKeys.AddAccImapPort,               "IMAP Port:");
            Set(StringKeys.AddAccImapSsl,                "Use SSL/TLS for IMAP");
            Set(StringKeys.AddAccSmtpServer,             "SMTP Host & Port:");
            Set(StringKeys.AddAccSmtpPort,               "SMTP Port:");
            Set(StringKeys.AddAccSmtpSsl,                "Use SSL/TLS for SMTP");
            Set(StringKeys.AddAccOAuthSignIn,            "Sign in with Microsoft");
            Set(StringKeys.AddAccOAuthSuccess,           "Microsoft OAuth signed in successfully!");
            Set(StringKeys.AddAccOAuthClickHelp,         "Click above to sign in via your web browser.");
            Set(StringKeys.AddAccHelpGmail,              "💡 For Gmail: Use a 16-character Google App Password (myaccount.google.com/apppasswords). Standard Google passwords will not work with 2FA enabled.");
            Set(StringKeys.AddAccTestConnection,         "Test Connection");
            Set(StringKeys.AddAccTesting,                "Testing connection...");
            Set(StringKeys.AddAccSave,                   "Save Account");
            Set(StringKeys.AddAccCancel,                 "Cancel");

            // --- 6. Settings View ---
            Set(StringKeys.SettingsTitle,                "Settings");
            Set(StringKeys.SettingsSecAiBackend,         "🤖  AI Engine & LLM Backend");
            Set(StringKeys.SettingsBackendSelect,        "Select Inference Backend:");
            Set(StringKeys.SettingsBackendLlama,         "🦙  Local llama.cpp");
            Set(StringKeys.SettingsBackendOllama,        "🦙  Local Ollama");
            Set(StringKeys.SettingsBackendCloud,         "☁️  Cloud / Custom API");
            Set(StringKeys.SettingsBackendNoAi,          "🚫  No AI (Disabled)");
            Set(StringKeys.SettingsBatteryWarningTitle,  "⚡  Running in No AI Mode (Battery Saver Active)");
            Set(StringKeys.SettingsBatteryWarningDesc,   "AI summarization and priority ranking are temporarily suspended because this device is running on battery power. Your configured settings below remain saved and will automatically resume when plugged into AC power.");
            Set(StringKeys.SettingsLlamaModelPath,       "GGUF Model File Path:");
            Set(StringKeys.SettingsLlamaLayers,          "GPU Layers (-ngl):");
            Set(StringKeys.SettingsLlamaPort,            "Server Port:");
            Set(StringKeys.SettingsLlamaContext,         "Context Size (-c):");
            Set(StringKeys.SettingsLlamaUrl,             "OpenAI Chat Endpoint URL:");
            Set(StringKeys.SettingsLlamaAutoStart,       "Auto-start llama-server on demand");
            Set(StringKeys.SettingsLlamaInstantVram,     "Instant VRAM Unload (free GPU memory when batch finishes; uncheck to keep model warm in memory)");
            Set(StringKeys.SettingsOllamaInfo,           "💡 Connects directly to local Ollama. Ensure Ollama is running (`ollama serve` or desktop app).");
            Set(StringKeys.SettingsOllamaUrl,            "Ollama Endpoint URL:");
            Set(StringKeys.SettingsOllamaModel,          "Ollama Model Name (e.g. llama3.2, qwen2.5:3b, mistral):");
            Set(StringKeys.SettingsSuggestions,          "Suggestions:");
            Set(StringKeys.SettingsCloudPreset,          "Provider Preset:");
            Set(StringKeys.SettingsCloudPresetSelect,    "(Select Provider Preset...)");
            Set(StringKeys.SettingsCloudUrl,             "API Endpoint URL (/v1/chat/completions):");
            Set(StringKeys.SettingsCloudKey,             "API Key (Bearer Token):");
            Set(StringKeys.SettingsCloudShow,            "Show");
            Set(StringKeys.SettingsCloudHide,            "Hide");
            Set(StringKeys.SettingsCloudModel,           "Model ID / Name (e.g. gpt-4o-mini, deepseek-chat):");
            Set(StringKeys.SettingsNoAiTitle,            "🚫  No AI Mode (Classic Email Client Mode)");
            Set(StringKeys.SettingsNoAiDisclaimer,       "Disclaimer & Mode Information:\r\n• Zero AI Overhead: LLM servers, background inference, and GPU/VRAM model loading are completely disabled.\r\n• Full Reading Pane: The AI Summary box is hidden, allowing the email body viewer to expand to 100% height.\r\n• Clean Inbox: The Priority ranking column (⚡) is removed from the inbox list for a clean, classic view.\r\n• Instant Fetching: Emails are synced directly via IMAP without prompt generation or summarization delays.\r\n\r\nClick '💾 Save Settings' at the bottom to apply and save this configuration.");
            Set(StringKeys.SettingsTemp,                 "Temperature:");
            Set(StringKeys.SettingsTempDesc,             "0.0 = Deterministic, 1.0+ = Creative");
            Set(StringKeys.SettingsMaxTokens,            "Max Response Tokens:");
            Set(StringKeys.SettingsMaxTokensDesc,        "Budget for summary length");
            Set(StringKeys.SettingsTokenTip,             "💡 Tip: Lower temperature (0.1 - 0.3) produces consistent, objective executive summaries.");
            Set(StringKeys.SettingsEmailLimitHeader,     "Email Ingestion Character Limit:");
            Set(StringKeys.SettingsEmailLimitDesc,       "Limits the raw email body length sent to the AI model. Truncation keeps prompts fast and prevents VRAM context overflows.");
            Set(StringKeys.SettingsUnlimited,            "Unlimited (Send Full Body)");
            Set(StringKeys.SettingsPresets,              "Presets:");
            Set(StringKeys.SettingsCharsDefault,         "4,000 chars (Default)");
            Set(StringKeys.SettingsChars8k,              "8,000 chars");
            Set(StringKeys.SettingsChars16k,             "16,000 chars");
            Set(StringKeys.SettingsChars32k,             "32,000 chars");
            Set(StringKeys.SettingsCharsUnlimited,       "♾️ Unlimited");
            Set(StringKeys.SettingsSecBattery,           "🔋  Battery Saver Mode");
            Set(StringKeys.SettingsBatteryDisableAi,     "Disable AI when on battery power (Auto No AI Mode)");
            Set(StringKeys.SettingsBatteryDesc,          "When enabled, the app automatically switches to No AI mode whenever your laptop is running on battery power to conserve battery life. Your configured AI backend is preserved and will resume when connected to AC power.");
            Set(StringKeys.SettingsBatteryActive,        "● Running on battery power: AI suspended");
            Set(StringKeys.SettingsBatteryAc,            "● Connected to AC power: AI operational");
            Set(StringKeys.SettingsSecLanguage,          "🌐  Language & Region");
            Set(StringKeys.SettingsLanguageLabel,        "Interface Language:");
            Set(StringKeys.SettingsLanguageDesc,         "Select the interface language for Kerkenez Mail.");
            Set(StringKeys.SettingsSecEmail,             "📬  Email Fetching Configuration");
            Set(StringKeys.SettingsMaxEmails,            "Max Emails per Account:");
            Set(StringKeys.SettingsOnlyUnread,           "Fetch only unread messages (uncheck to pull all recent emails from INBOX)");
            Set(StringKeys.SettingsMarkAsSeen,           "Mark emails as read on IMAP server upon fetching (\\Seen flag)");
            Set(StringKeys.SettingsMultiSelectPreview,   "Multi-select preview email (Ctrl+click):");
            Set(StringKeys.SettingsMultiSelectLast,      "Show last selected email (Default)");
            Set(StringKeys.SettingsMultiSelectFirst,     "Show first selected email");
            Set(StringKeys.SettingsSecAttachments,       "📁  Attachment Downloads");
            Set(StringKeys.SettingsDownloadPathHeader,   "Default Download Folder:");
            Set(StringKeys.SettingsDownloadPathDesc,     "Location where email attachments will be saved by default (defaults to your Windows Downloads folder).");
            Set(StringKeys.SettingsDownloadPathSelectDesc, "Select Default Attachment Download Folder");
            Set(StringKeys.SettingsBrowse,               "Browse...");
            Set(StringKeys.SettingsDefault,              "Default");
            Set(StringKeys.SettingsSecUi,                "🖥️  Interface & Layout");
            Set(StringKeys.SettingsCollapseSidebar,      "Start with left sidebar collapsed by default (compact icon rail on launch)");
            Set(StringKeys.SettingsScalingHeader,        "Default Launch Window Scaling (Relative to Display):");
            Set(StringKeys.SettingsScalingDesc,          "Target proportion of the active monitor's usable desktop area (working area) on launch (Default: 60% width × 56% height).");
            Set(StringKeys.SettingsWidthScale,           "Width Scale (%):");
            Set(StringKeys.SettingsHeightScale,          "Height Scale (%):");
            Set(StringKeys.SettingsResizeActive,         "Resize Active Window");
            Set(StringKeys.SettingsPresetDefault,        "60% × 56% (Default)");
            Set(StringKeys.SettingsPresetCompact,        "50% × 50% (Compact)");
            Set(StringKeys.SettingsPresetLarge,          "75% × 70% (Large)");
            Set(StringKeys.SettingsPresetMax,            "95% × 90% (Near Max)");
            Set(StringKeys.SettingsLaunchDimensions,     "Persistent launch dimensions: {0} × {1} px (Display working area: {2} × {3} px)");
            Set(StringKeys.SettingsAddShortcuts,         "Add Desktop & Start Menu Shortcuts");
            Set(StringKeys.SettingsShortcutsSuccess,     "Shortcuts created on Desktop and Start Menu successfully!");
            Set(StringKeys.SettingsShortcutsError,       "Could not create shortcuts.");
            Set(StringKeys.SettingsSecTray,              "🔔  System Tray Daemon & Notifications");
            Set(StringKeys.SettingsAlwaysKeepOn,         "Always keep on (Run system tray daemon in background)");
            Set(StringKeys.SettingsEnableTrayNotifs,      "Enable Windows desktop notifications");
            Set(StringKeys.SettingsCheckInterval,        "Check interval (minutes):");
            Set(StringKeys.SettingsStartWithWindows,     "Start system tray daemon on user log-in");
            Set(StringKeys.SettingsRestartDaemon,        "Restart / Start Tray Daemon");
            Set(StringKeys.SettingsSecPrompt,            "✍️  AI System Prompt Template");
            Set(StringKeys.SettingsBtnSave,              "Save Settings");
            Set(StringKeys.SettingsBtnReset,             "Reset Defaults");
            Set(StringKeys.SettingsBtnTestLlm,           "Test LLM Connection");
            Set(StringKeys.SettingsSavedToast,           "Settings saved successfully!");
            Set(StringKeys.SettingsResetConfirm,         "Are you sure you want to reset all settings to defaults?");

            // --- 7. Live Logs View ---
            Set(StringKeys.LogsTitle,                    "Live Logs");
            Set(StringKeys.LogsSubtitle,                 "Real-time diagnostic events, IMAP connections, and AI inference logs.");
            Set(StringKeys.LogsBtnCopy,                  "Copy Logs");
            Set(StringKeys.LogsBtnClear,                 "Clear Logs");
            Set(StringKeys.LogsBtnExport,                "Export Logs...");
            Set(StringKeys.LogsChkAutoScroll,            "Auto-scroll to latest");
            Set(StringKeys.LogsCopiedMsg,                "Console log copied to clipboard!");

            // --- 8. Common & Dialog Messages ---
            Set(StringKeys.CommonSave,                   "Save");
            Set(StringKeys.CommonCancel,                 "Cancel");
            Set(StringKeys.CommonClose,                  "Close");
            Set(StringKeys.CommonDelete,                 "Delete");
            Set(StringKeys.CommonOk,                     "OK");
            Set(StringKeys.CommonYes,                    "Yes");
            Set(StringKeys.CommonNo,                     "No");
            Set(StringKeys.CommonError,                  "Error");
            Set(StringKeys.CommonWarning,                "Warning");
            Set(StringKeys.CommonSuccess,                "Success");
            Set(StringKeys.CommonLoading,                "Loading...");
            Set(StringKeys.CommonConnecting,             "Connecting...");

            // --- 9. Status Bar & Metrics ---
            Set(StringKeys.StatusSyncComplete,           "Sync complete");
            Set(StringKeys.StatusReady,                  "Ready");
            Set(StringKeys.StatusReadyEmails,            "Ready • {0} emails in inbox ({1} unread)");
            Set(StringKeys.StatusReadyFolder,            "Ready • {0} emails in {1}");
            Set(StringKeys.StatusAccountsCount,          "Accounts: {0} | VRAM: {1}");
            Set(StringKeys.StatusAccountsBackend,        "Accounts: {0} | Backend: {1}");
            Set(StringKeys.StatusReadyBackend,           "Ready • Backend: {0}");
            Set(StringKeys.StatusVramFree,               "VRAM Free");
            Set(StringKeys.StatusModelLoaded,            "Model Loaded in VRAM");
            Set(StringKeys.StatusOllamaActive,           "Ollama Active");
            Set(StringKeys.StatusCloudActive,            "Cloud Active");
            Set(StringKeys.StatusAiDisabled,             "AI Disabled");
            Set(StringKeys.StatusBatterySaverNoAi,       "Battery Saver (No AI)");
            Set(StringKeys.StatusOnDemandVram,           "On-Demand (VRAM Unload)");
            Set(StringKeys.StatusSummaryReady,           "Summary ready");
            Set(StringKeys.StatusSyncingFolder,          "Syncing {0}...");
            Set(StringKeys.StatusNoAccounts,             "No accounts configured");
            Set(StringKeys.StatusLiveConnecting,         "Live IMAP: Connecting...");
            Set(StringKeys.StatusLiveListening,          "Live IMAP: Connected & Listening");
            Set(StringKeys.StatusLiveStopped,            "Live IMAP: Stopped");
            Set(StringKeys.StatusLiveDone,               "Live IMAP: Transmitting DONE signals...");
            Set(StringKeys.StatusLiveNewEmail,           "Live IMAP: New email arrived for {0}");
            Set(StringKeys.StatusStartingUp,             "Starting up...");
            Set(StringKeys.StatusDisabledClassic,        "Disabled (Classic Mail)");
            Set(StringKeys.StatusModelLoadFailed,        "Model could not be loaded");
        }
    }
}
